version: '3.7'

services:
  djangogram:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./djangogram:/djangogram"
    command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    environment:
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=1
      - DB_NAME=djangogram_db
      - DB_HOST=db
      - DB_USER=my_user
      - DB_PASS=my_password
    depends_on:
      - db
  
  db:
    build:
      context: ./postgres_dpl
